### ISSUE TITLE
Push changes.

### ISSUE THREAD

**Issue by RobertASmith** [RobertASmith/shiny_healthy_economics#2]
Hi @sebates1 can you push your changes. No worries on where you are at, I just don't want to create merge conflicts with file structures etc.

Once you push if you branch off, I'll also branch off and we can merge both back into the master later.

Cheers,

Rob

Have a pic of Rudi (just because we can)

![IMGP1662](https://user-images.githubusercontent.com/41961614/93065286-6d600200-f670-11ea-86b9-685f19659bdf.jpg)

**Comment by sebates1** [comment]
Think I've done it? I've put a file in each session otherwise the folder would show up as a change but other than session 2, which I'm working on, the others are just a blank template file.

To branch off do I just select the button to the left of "master" in R (git panel) - don't want to mess anything up!

Aww Rudi!

**Comment by RobertASmith** [comment]
That's perfect yeah. 

Yeah select this one (below) and it'll make a branch for you (maybe call it sarah_1 or something). Then you can work on there while I work on another branch I'm about to make, then when you are ready to merge your branch back in make a pull request with me as the 'reviewer' and I'll do the same vice-versa.

![image](https://user-images.githubusercontent.com/41961614/93066642-25da7580-f672-11ea-8047-191603f531fb.png)

**Comment by sebates1** [comment]
ok, I've done that - I'll work on this branch! Thanks for the help!
